name: Build Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set NODE_ENV to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build
        run: npm run build

      - name: Check for build success
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: 'npm run build' failed"
            exit 1
          fi
